### ISSUE TITLE
Question about `run_make_list.sh`

### ISSUE THREAD

**Issue by zhiyozhao** [hvkwak/PIE-NET_Dataset_Preparation#4]
My recently downloaded ABC Dataset is formed in the following manner:
* 100 chunks in total: 0000-0099
* each chunk contains 10000 models: 00000000-00009999, model folders are under chunk folder
* each model folder may or may not contain annotation files

Thus, for `.yml` file of chunk 0000, it's like:
```
0000_feat/00009982/00009982_8fd881580c344a9583659586_features_016.yml
0000_feat/00009986/00009986_ba508426162c40128d0c7a2a_features_000.yml
0000_feat/00009987/00009987_ba508426162c40128d0c7a2a_features_001.yml
0000_feat/00009988/00009988_ba508426162c40128d0c7a2a_features_002.yml
0000_feat/00009989/00009989_ba508426162c40128d0c7a2a_features_003.yml
0000_feat/00009993/00009993_0dc78076fcce4a67864e71d4_features_000.yml
0000_feat/00009994/00009994_ea83e2f413614058bcfa17e1_features_000.yml
0000_feat/00009996/00009996_6980d41656c4406383dc8b46_features_001.yml
0000_feat/00009998/00009998_6980d41656c4406383dc8b46_features_003.yml
0000_feat/00009999/00009999_003df34c1a7b4dc2bd43c5f4_features_000.yml
```

In line 19 of `run_make_list.sh`: `cp $dir_feat/${line1}/*.yml ${line1}`

It seems to me that `run_make_list.sh` cannot handle this correctly. The code seems to assume that all annotation files are located directly under the chunk folder, e.g. `0000_feat/xxx_features_xxx.yml`.

So my question: Was the ABC Dataset updated since the creation of this code, or did I misunderstood something? If the dataset organization is changed, what else do I need to change besides the `run_make_list.sh`?

**Comment by hvkwak** [comment]
Hi. This is just a simple bash script that copies .yml files to obj folders for further dataset preparation. Note that you should change directories of `dir_obj` or `dir_feat` in the script accordingly, because it was what's for my local computer. Or you may just deal with the directories accordingly. 

ABC Dataset may have not been updated, check for updates though in the project page. I remember that almost all files had annotation files, one or two of them probably missing. Hope it helps.

**Comment by bingpeng2022** [comment]
Hello, I have encountered the same problem in my research, I would like to ask you how you solved it and I would like your help.
